---
- name: config | Configuring Chrony
  template:
    src: etc/chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart chrony

- name: config | Configuring Kerberos
  template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

# - name: config | Configuring Realm
#   template:
#     src: etc/realmd.conf.j2
#     dest: /etc/realmd.conf
#     owner: root
#     group: root
#   become: true

- name: config | Configuring Samba
  template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart smbd
    - restart nmbd

- name: config | Configuring SSSD
  template:
    src: etc/sssd/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  become: true
  notify:
    - restart sssd

# - name: update systemd service unit
#   ini_file:
#     path: /lib/systemd/system/sssd.service
#     section: "{{ item.section }}"
#     option: "{{ item.option }}"
#     value: "{{ item.value }}"
#     no_extra_spaces: yes
#   become: true
#   with_items:
#     - section: Service
#       option: ExecStartPre
#       value: "/bin/rm -rf /var/run/sssd.pid || true"
#     - section: Service
#       option: Restart
#       value: always
#   notify: reload systemd config

- name: config | Configuring /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[inventory_hostname]['ansible_host'] + ' ' + ansible_hostname }}"
    line: "{{ hostvars[inventory_hostname]['ansible_host'] + ' ' + ansible_hostname + ' ' + ansible_hostname + '.' + sssd_primary_domain_name }}"
    state: present
  become: true
