---
- name: debian | Installing SSSD Packages
  apt:
    name:
      - adcli
      - krb5-user
      - libnss-sss
      - libpam-sss
      - packagekit
      - python-pexpect
      - python3-pexpect
      - realmd
      - samba-common-bin
      - sssd
      - sssd-tools
    state: present
  become: true
  register: result
  until: result is successful
