---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  # - name: centos7
  #   box: mrlesmithjr/centos7
  # - name: centos8
  #   box: mrlesmithjr/centos8
  # - name: debian9
  #   box: mrlesmithjr/stretch64
  # - name: debian10
  #   box: mrlesmithjr/buster64
  # - name: ubuntu1604
  #   box: mrlesmithjr/xenial64
  - name: ubuntu1804
    box: mrlesmithjr/bionic64
    interfaces:
      - auto_config: true
        ip: 192.168.250.11
        network_name: private_network
        type: static
    groups:
      - domain_clients
  - name: windows2019
    box: mrlesmithjr/windows2019
    instance_raw_config_args:
      - "vm.guest = :windows"
      - "vm.communicator = :winrm"
      - "winrm.transport = :ssl"
      - "winrm.ssl_peer_verification = false"
    interfaces:
      - auto_config: true
        ip: 192.168.250.10
        network_name: private_network
        type: static
    groups:
      - domain_controllers
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 306
  playbooks:
    converge: playbook.yml
  inventory:
    host_vars:
      ubuntu1804:
        netplan_configuration:
          network:
            version: 2
            ethernets:
              enp0s3:
                dhcp4: true
                # nameservers:
                #   addresses:
                #     - 192.168.250.10
                #   search:
                #     - "{{ pri_domain_name }}"
              enp0s8:
                addresses:
                  - 192.168.250.11/24
                nameservers:
                  addresses:
                    - 192.168.250.10
                  search:
                    - "{{ pri_domain_name }}"
      windows2019:
        ansible_host: 192.168.250.10
        ansible_port: 5986
    group_vars:
      all:
        pri_domain_name: vagrant.local
      domain_clients:
        etc_hosts_pri_dns_name: "{{ pri_domain_name }}"
        netplan_pri_domain: "{{ pri_domain_name }}"
        ntp_pri_domain_name: "{{ pri_domain_name }}"
        ntp_servers:
          - 192.168.250.10
        sssd_config: true
      domain_controllers:
        ansible_connection: winrm
        ansible_password: vagrant
        ansible_user: vagrant
        ansible_winrm_server_cert_validation: ignore
        sudo: false
        windows_domain_admin_rsat: true
        windows_domain_info:
          dns_domain_name: "{{ pri_domain_name }}"
          safe_mode_password: Vagrant@123!
verifier:
  name: testinfra
  lint:
    name: flake8
  additional_files_or_dirs:
    - ../shared/*
