---
- name: Prepare
  hosts: domain_clients
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal) || (sudo yum -y install python3 && sudo alternatives --set python /usr/bin/python3)
      become: true
      changed_when: false

- name: Provision Domain Controllers
  hosts: domain_controllers
  roles:
    - role: ansible-windows-dns-server

- name: Capture Primary Domain Controller
  hosts: domain_controllers
  tasks:
    - name: Setting Primary Domain Controller
      set_fact:
        windows_primary_domain_controller: "{{ groups['domain_controllers'][0] }}"

- name: Provision Domain Controllers
  hosts: domain_controllers
  roles:
    - role: ansible-windows-domain
      when:
        - inventory_hostname == windows_primary_domain_controller
