---
- src: https://github.com/mrlesmithjr/ansible-etc-hosts.git
- src: https://github.com/mrlesmithjr/ansible-netplan.git
- src: https://github.com/mrlesmithjr/ansible-ntp.git
- src: https://github.com/mrlesmithjr/ansible-windows-dns-server.git
- src: https://github.com/mrlesmithjr/ansible-windows-domain.git
